### ISSUE TITLE
Monster és Creature különszedése Scene-hez adáskor

### ISSUE THREAD

**Issue by HontiSz** [badacsonyigorenyember/DnDSimulator#15]
Most minden Creature és Monster egymezőben van, amikor behúzzuk a Scene-re.
Ezt kellene lecserélni úgy, hogy a Creature-ök és Monster-ek külön panelban legyenek kilistázva, mert ha Monster-t húzunk be, akkor az egy új Creature-ként jön létre, de ha Creature-t húzunk be, akkor a már létező Creature jelenik majd meg a Scene-en.

Azt is meg lehetne akkor már oldani, hogy a Creature-ök is kettő részre legyenek szedve:
- Creature => azok a Creature-ök, amik sokszor szerepelnek (pl az egyik Scene-en létrehoztunk 20 goblint, akkor azok valszeg nem fognak kelleni másikon)
- CustomCreature => azok a Creature-ök, amik több helyen is szerepelhetnek (pl az egyik Scene-en van egy boss fight, de nem azzal végződik, hogy legyőzik, hanem elmenekül, és lehet egy másik Scene-en lesz a round 2, vagy éppen amikor legyőzik, akkor nem ölik meg, hanem elviszik a hatóságoknak)

**Comment by badacsonyigorenyember** [comment]
Meg lett valósítva a #2 issue-ban
